version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - ./src:/app/src
      - ./index:/app/index
      - ./.cache/hf:/app/.cache/huggingface
    restart: unless-stopped
    profiles: ["dev"]

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./index:/app/index
      - ./.cache/hf:/app/.cache/huggingface
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"] # 覆盖 dev 的 --reload
    restart: unless-stopped
    profiles: ["prod"]
